asl_mfree.o: asl_mfree.cc \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/extras/include/newmat/newmat.h \
  /Users/univ1102/fsl/extras/include/newmat/include.h \
  /Users/univ1102/fsl/extras/include/newmat/boolean.h \
  /Users/univ1102/fsl/extras/include/newmat/myexcept.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatio.h \
  /Users/univ1102/fsl/include/newimage/newimageall.h \
  /Users/univ1102/fsl/include/newimage/newimage.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/include/newimage/lazy.h \
  /Users/univ1102/fsl/include/newimage/lazyiterators.h \
  /Users/univ1102/fsl/include/newimage/positerators.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h \
  /Users/univ1102/fsl/include/fslio/fslio.h \
  /Users/univ1102/fsl/include/niftiio/nifti1_io.h \
  /Users/univ1102/fsl/include/niftiio/nifti1.h \
  /Users/univ1102/fsl/include/znzlib/znzlib.h \
  /Users/univ1102/fsl/include/znzlib/znzlib.h \
  /Users/univ1102/fsl/include/fslio/dbh.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/include/miscmaths/kernel.h \
  /Users/univ1102/fsl/extras/include/newmat/newmat.h \
  /Users/univ1102/fsl/include/miscmaths/kernel.h \
  /Users/univ1102/fsl/include/niftiio/nifti1.h \
  /Users/univ1102/fsl/include/miscmaths/splinterpolator.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h \
  /Users/univ1102/fsl/include/newimage/newimageio.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatio.h \
  /Users/univ1102/fsl/include/newimage/complexvolume.h \
  /Users/univ1102/fsl/include/fslio/fslio.h \
  /Users/univ1102/fsl/include/newimage/newimagefns.h \
  /Users/univ1102/fsl/include/newimage/imfft.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h \
  /Users/univ1102/fsl/include/utils/tracer_plus.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatio.h \
  /Users/univ1102/fsl/include/utils/time_tracer.h readoptions.h \
  /Users/univ1102/fsl/include/utils/options.h \
  /Users/univ1102/fsl/include/utils/log.h asl_mfree_functions.h
asl_mfree_functions.o: asl_mfree_functions.cc asl_mfree_functions.h \
  /Users/univ1102/fsl/include/newimage/newimageall.h \
  /Users/univ1102/fsl/include/newimage/newimage.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/extras/include/newmat/newmat.h \
  /Users/univ1102/fsl/extras/include/newmat/include.h \
  /Users/univ1102/fsl/extras/include/newmat/boolean.h \
  /Users/univ1102/fsl/extras/include/newmat/myexcept.h \
  /Users/univ1102/fsl/include/newimage/lazy.h \
  /Users/univ1102/fsl/include/newimage/lazyiterators.h \
  /Users/univ1102/fsl/include/newimage/positerators.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h \
  /Users/univ1102/fsl/include/fslio/fslio.h \
  /Users/univ1102/fsl/include/niftiio/nifti1_io.h \
  /Users/univ1102/fsl/include/niftiio/nifti1.h \
  /Users/univ1102/fsl/include/znzlib/znzlib.h \
  /Users/univ1102/fsl/include/znzlib/znzlib.h \
  /Users/univ1102/fsl/include/fslio/dbh.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/include/miscmaths/kernel.h \
  /Users/univ1102/fsl/extras/include/newmat/newmat.h \
  /Users/univ1102/fsl/include/miscmaths/kernel.h \
  /Users/univ1102/fsl/include/niftiio/nifti1.h \
  /Users/univ1102/fsl/include/miscmaths/splinterpolator.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h \
  /Users/univ1102/fsl/include/newimage/newimageio.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatio.h \
  /Users/univ1102/fsl/include/newimage/complexvolume.h \
  /Users/univ1102/fsl/include/fslio/fslio.h \
  /Users/univ1102/fsl/include/newimage/newimagefns.h \
  /Users/univ1102/fsl/include/newimage/imfft.h \
  /Users/univ1102/fsl/include/miscmaths/miscmaths.h
readoptions.o: readoptions.cc readoptions.h \
  /Users/univ1102/fsl/include/utils/options.h \
  /Users/univ1102/fsl/include/utils/log.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatap.h \
  /Users/univ1102/fsl/extras/include/newmat/newmat.h \
  /Users/univ1102/fsl/extras/include/newmat/include.h \
  /Users/univ1102/fsl/extras/include/newmat/boolean.h \
  /Users/univ1102/fsl/extras/include/newmat/myexcept.h \
  /Users/univ1102/fsl/extras/include/newmat/newmatio.h \
  /Users/univ1102/fsl/include/utils/tracer_plus.h \
  /Users/univ1102/fsl/include/utils/time_tracer.h
